# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qz_aSYNGWNuV2ewm2bMxj-8L8oKwOlX0
"""

import random
import string

def generate_strong_password(length):
    if length < 4:
        return "Password length should be at least 4."

  # ❤️❤️
    lower = random.choice(string.ascii_lowercase)
    upper = random.choice(string.ascii_uppercase)
    digit = random.choice(string.digits)
    symbol = random.choice(string.punctuation)


    remaining = ''.join(random.choice(string.ascii_letters + string.digits + string.punctuation)
                        for _ in range(length - 4))

   #💕💕😒
    password_list = list(lower + upper + digit + symbol + remaining)
    random.shuffle(password_list)

    return ''.join(password_list)

print("=== Strong Password Generator ===")
length = int(input("Enter password length: "))
print("Generated Strong Password:", generate_strong_password(length))

